os: linux
group: travis_latest
compiler: gcc
language: cpp
dist: bionic


before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -q update

install:
  - sudo apt-get -y install libgtest-dev g++-9
  - mkdir /tmp/gtest && pushd /tmp/gtest
  - cmake /usr/src/gtest
  - make
  - sudo make install
  - popd

env:
  global:
    - CXX=g++-9

jobs:
    - stage: JDI Tests
      env: CMAKE_AND_GTEST=1
      script:
        - cmake CMakeLists.txt
        - make
        - bin/Test/JustDefineIt
    - stage: JDI Tests
      env: ENIGMA_MASTER_TEST=1
      install:
        - sudo apt-get -y install g++-9 libprotobuf-dev protobuf-compiler libpng-dev zlib1g-dev
      script:
        - git clone --depth 1 https://github.com/enigma-dev/enigma-dev.git /tmp/enigma-dev
        - pushd /tmp/enigma-dev
        - rm -rf CompilerSource/JDI
        - cp -R ${TRAVIS_BUILD_DIR} CompilerSource/JDI
        - make
        - popd

