jobs:
- job: MINGW
  pool:
    vmImage: windows-latest
  strategy:
    matrix:
      i686:
        MINGW_UPPER: MINGW32
        MINGW_LOWER: mingw32
        MINGW_ARCH: i686
      x86_64:
        MINGW_UPPER: MINGW64
        MINGW_LOWER: mingw64
        MINGW_ARCH: x86_64
  
  steps:
    - checkout: self
      submodules: true
      
    - powershell: |
        choco install msys2 /InstallDir %CD:~0,2%\msys64
      displayName: Install MSYS2
    
    - script: |
        set PATH=%CD:~0,2%\msys64\usr\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
        %CD:~0,2%\msys64\usr\bin\pacman --noconfirm -Syyuu
        %CD:~0,2%\msys64\usr\bin\pacman --noconfirm --needed -S git base-devel mingw-w64-$(MINGW_ARCH)-toolchain mingw-w64-$(MINGW_ARCH)-cmake mingw-w64-$(MINGW_ARCH)-gtest
        %CD:~0,2%\msys64\usr\bin\pacman --noconfirm -Scc
      displayName: Install Toolchain
    
    - script: |
        set PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
        %CD:~0,2%\msys64\usr\bin\bash -lc "bash cmake CMakeLists.txt"
      displayName: 'CMake Generate Makefiles'
      env:
        MSYSTEM: $(MINGW_UPPER)
        CHERE_INVOKING: yes
        MINGW_INSTALLS: $(MINGW_LOWER)
        
    - script: |
        set PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
        %CD:~0,2%\msys64\usr\bin\bash -lc "bash cmake CMakeLists.txt"
      displayName: 'CMake Generate Makefiles'
      env:
        MSYSTEM: $(MINGW_UPPER)
        CHERE_INVOKING: yes
        MINGW_INSTALLS: $(MINGW_LOWER)
